const SITE_SET_LOCALE = 'SITE_SET_LOCALE'
const SITE_SET_PATH = 'SITE_SET_PATH'
const SITE_SET_WORKING = 'SITE_SET_WORKING'

export default {
    SITE_SET_LOCALE,
    SITE_SET_PATH,
    SITE_SET_WORKING
}